### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by krthr** [BorderlessLabs/json-rpc#1]
I think there is a typo in the README.

You import the `createHandler` method but you use `createRpc`.

**Comment by blakeembrey** [comment]
Thanks, had trouble naming the method this morning. I'll align the example and change it to `createServer` instead - I intended to create a client alongside and this should make it clearer.

**Comment by blakeembrey** [comment]
Closed with https://github.com/BorderlessLabs/json-rpc/releases/tag/v1.1.0.
