### ISSUE TITLE
Issue detected with Zod

### ISSUE THREAD

**Issue by colinhacks** [BorderlessLabs/json-rpc#3]
Love your work on this package, type-safe RPC is long overdue.

Just wanted to warn you that I found a bug in the inferred types of merged object schemas last night. It's now fixed in zod@1.0.12 but I don't want you to get caught off guard. I'm implementing more thorough testing of the codebase to make sure this doesn't happen again...correct inferred types are kinda the whole reason I made zod so I feel a little dumb 😅

**Comment by blakeembrey** [comment]
@vriad Thanks for the heads up! Unfortunately trying out `zod` was extremely short lived and I probably shouldn't have published it (it was quickly reverted). I actually run into some limitations of it, which were pretty minimal but become obvious in production. I can list them out here and if you want to fix them I can try using it again:

* `any` - sometimes I want to just toss whatever I have over the wire (e.g. it comes from a library or third-party I trust is typed)
* `record` - a dictionary type of `Record<T, U>`

Actually, I guess those are the only two I can see right now.
